repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
        files: ^dataset\.json$
  - repo: local
    hooks:
      - id: check-nulls
        name: Check for null values in dataset.json
        entry: scripts/check_nulls.py
        language: script
        files: ^dataset\.json$
        types: [file]
