name: Push data to HuggingFace

on:
  push:
    branches: [ main ]

jobs:
  push_to_hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create and push dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python push_data_to_huggingface.py
