name: Validate JSON

on:
  push:
    branches:
      - main # Trigger on pushes to main
      # Remove branches-ignore if you want it to run on all branches
  pull_request:
    branches:
      - main

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Validate dataset.json
        run: jq . dataset.json > /dev/null
